language: minimal

dist: bionic

services:
  - docker

before_install:
  - sudo apt-get install -y make

jobs:
  include:
    - stage: lint
      name: shellcheck
      script: make shellcheck
    - stage: unit
      name: make unit
    - stage: scenarios
      name: simple
      script: make simple
    - stage: scenarios
      name: service
      script: make service
    - stage: scenarios
      name: dind
      script: make dind
    - stage: scenarios
      name: shell
      script: make shell
    - stage: scenarios
      name: escapes
      script: make escapes
    - stage: scenarios
      name: pipeline
      script: make examples/pipeline
