version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: lint
          command: make shellcheck
      - run:
          name: unit
          command: make unit
      - run:
          name: small
          command: make small
      - run:
          name: service
          command: make service
      - run:
          name: dind
          command: make dind

