version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - checkout
    - run:
        name: commitlint
        command: make commitlint
    - run:
        name: shellcheck
        command: make shellcheck
    - run:
        name: unit
        command: make unit
    - run:
        name: simple
        command: make simple
    - run:
        name: multi-images
        command: make multi-images
    - run:
        name: service
        command: make service
    - run:
        name: dind
        command: make dind
    - run:
        name: shell
        command: make shell
    - run:
        name: trap
        command: make trap
    - run:
        name: implicit-job
        command: make implicit-job
    - run:
        name: escapes
        command: make escapes
    - run:
        name: stdout
        command: make stdout
    - run:
        name: pipeline
        command: make examples/pipeline
