name: CI

on: [push]

jobs:
  pipeline:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: commitlint
      run: make commitlint
    - name: shellcheck
      run: make shellcheck
    - name: unit
      run: make unit
    - name: simple
      run: make simple
    - name: multi-images
      run: make multi-images
    - name: service
      run: make service
    - name: dind
      run: make dind
    - name: shell
      run: make shell
    - name: trap
      run: make trap
    - name: implicit-job
      run: make implicit-job
    - name: escapes
      run: make escapes
    - name: stdout
      run: make stdout
    - name: pipeline
      run: make examples/pipeline