name: CI

on: [push]

jobs:
  pipeline:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: shellcheck
      run: make shellcheck
    - name: small
      run: make small
    - name: service
      run: make service
    - name: dind
      run: make dind
