name: CI

on: [push]

jobs:
  pipeline:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: shellcheck
      run: make shellcheck
    - name: unit
      run: make unit
    - name: coverage
      run: make coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: simple
      run: make simple
    - name: service
      run: make service
    - name: dind
      run: make dind
    - name: escapes
      run: make escapes
    - name: pipeline
      run: make examples/pipeline